name: redis-caching

services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis-gui:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"